WORLD_SIZE: float = 600

START_CREATURE_SIZE: int = 10
START_CREATURE_COLOR: tuple = (10, 50, 50)
CREATURE_BORDER_COLOR: tuple = (7, 7, 7)
CREATURE_BORDER_WIDTH: int = 2

FOOD_BORDER_COLOR: tuple = (7, 7, 7)
FOOD_BORDER_WIDTH: int = 1
START_FOOD_SIZE: int = 7
START_FOOD_COLOR: tuple = (63, 155, 11)

FOOD_CREATE_DELAY: float = 0.002

HUNGER_TICK_DELAY: float = 0.8
EXTREME_HUNGER_VALUE: int = 65
EAT_DISTANCE: float = 17
BUSH_FOOD_VALUE: int = 35
  
MEAT_FOOD_VALUE: int = 60
KILL_TREATMENT: float = 60
DAMAGE_MULTIPLIER: float = 6.5
EXTREME_HP_VALUE: float = 1000
  
SPEED_HUNGER_MULTIPLIER: float = 0.25

PUSH_MULTIPLIER: float = 0.03
DAMPENING: float = 0.25

EVOLVE_HUNGER_VALUE: float = 200
EVOLVE_HUNGER_COST: float = 90

MAX_CREATURES: int = 100
MAX_FOOD: int = 500

BOT_CREATE_DELAY: float = 5

NAME_COLOR = (240, 240, 240)
NAME_FONT_SIZE = 17

SAVE_DELAY: float = 240

REPRODUCE_DELAY: float = 30
