WORLD_SIZE: float = 300

START_CREATURE_SIZE: int = 10
START_CREATURE_COLOR: tuple = (10, 50, 50)
CREATURE_BORDER_COLOR: tuple = (7, 7, 7)
CREATURE_BORDER_WIDTH: int = 1

FOOD_BORDER_COLOR: tuple = (7, 7, 7)
FOOD_BORDER_WIDTH: int = 1
START_FOOD_SIZE: int = 7
START_FOOD_COLOR: tuple = (63, 155, 11)

FOOD_CREATE_DELAY: float = 0.5

HUNGER_TICK_DELAY: float = 1
EXTREME_HUNGER_VALUE: int = 30
EAT_DISTANCE: float = 17
BUSH_FOOD_VALUE: int = 20
SPEED_HUNGER_MULTIPLIER: float = 0.25

PUSH_MULTIPLIER: float = 0.9
DAMPENING: float = 0.15

EVOLVE_HUNGER_VALUE: float = 150
EVOLVE_HUNGER_COST: float = 90