WORLD_SIZE: float = 600

START_CREATURE_SIZE: int = 10
START_CREATURE_COLOR: tuple = (10, 50, 50)
CREATURE_BORDER_COLOR: tuple = (7, 7, 7)
CREATURE_BORDER_WIDTH: int = 2

FOOD_BORDER_COLOR: tuple = (7, 7, 7)
FOOD_BORDER_WIDTH: int = 1
START_FOOD_SIZE: int = 7
START_FOOD_COLOR: tuple = (63, 155, 11)

FOOD_CREATE_DELAY: float = 0.21

HUNGER_TICK_DELAY: float = 1
EXTREME_HUNGER_VALUE: int = 30
EAT_DISTANCE: float = 17
BUSH_FOOD_VALUE: int = 23
  
MEAT_FOOD_VALUE: int = 60
KILL_TREATMENT: float = 60
  
SPEED_HUNGER_MULTIPLIER: float = 0.17

PUSH_MULTIPLIER: float = 0.4
DAMPENING: float = 0.13

EVOLVE_HUNGER_VALUE: float = 200
EVOLVE_HUNGER_COST: float = 90

MAX_CREATURES: int = 1000
MAX_FOOD: int = 500

BOT_CREATE_DELAY: float = 5

NAME_COLOR = (240, 240, 240)
NAME_FONT_SIZE = 25

BACKUP_DELAY: float = 240
